import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";

interface PresetAggregate {
  preset: string;
  caseCount: number;
  passed: number;
  heuristicFiredCount: number;
  totalRawTokens: number;
  totalReducedTokens: number;
  avgReductionPct: number | null;
}

interface PresetBenchmarkReport {
  tokenizer: string;
  aggregate: {
    totalCases: number;
    passed: number;
    heuristicFiredCount: number;
    totalRawTokens: number;
    totalReducedTokens: number;
    avgReductionPct: number | null;
  };
  byPreset: PresetAggregate[];
}

interface TestStatusFixtureReport {
  name: string;
  decision: string;
  primarySuspectKind: string;
  unknownBucketCount: number;
  primary: {
    raw: { chars: number; tokens: number };
    standard: { chars: number; tokens: number };
    focused: { chars: number; tokens: number };
    verbose: { chars: number; tokens: number };
    diagnoseJson: { chars: number; tokens: number };
  };
}

interface TestStatusBenchmarkReport {
  tokenizer: string;
  fixtures: TestStatusFixtureReport[];
  aggregate: {
    primary: {
      raw: { chars: number; tokens: number };
      standard: { chars: number; tokens: number };
      focused: { chars: number; tokens: number };
      verbose: { chars: number; tokens: number };
      diagnoseJson: { chars: number; tokens: number };
    };
  };
}

interface IncidentManifestEntry {
  id: string;
  title: string;
  artifactPath: string;
  currentArtifactPath?: string;
  exactTextRecovered: boolean;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..", "..");

function parseArgs(argv: string[]): { snapshotLabel?: string } {
  let snapshotLabel: string | undefined;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--snapshot") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--snapshot requires a label, for example --snapshot v0.3.3");
      }
      snapshotLabel = value.replace(/[^A-Za-z0-9._-]/g, "-");
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return { snapshotLabel };
}

function runJsonScript(args: string[]): unknown {
  const result = spawnSync(process.execPath, ["--import", "tsx", ...args], {
    cwd: repoRoot,
    encoding: "utf8"
  });

  if (result.status !== 0) {
    throw new Error(result.stderr || result.stdout || `Command failed: ${args.join(" ")}`);
  }

  return JSON.parse(result.stdout);
}

function ensureDir(dirPath: string): void {
  mkdirSync(dirPath, { recursive: true });
}

function formatPct(raw: number, reduced: number): string {
  if (raw === 0) {
    return "0.00%";
  }
  return `${(((raw - reduced) / raw) * 100).toFixed(2)}%`;
}

function summarizeIncidentDelta(args: {
  id: string;
  beforeText: string;
  afterText: string;
  recovered: boolean;
}): string[] {
  const lines: string[] = [];

  if (!args.recovered && args.id === "targeted-initial-sift-misroute") {
    lines.push("- Before: exact historical sift output was not recoverable.");
    lines.push(`- After: current targeted sift pass is concise and clean: \`${args.afterText.trim()}\``);
    return lines;
  }

  if (/Provider follow-up failed \(/.test(args.beforeText)) {
    lines.push("- Before: user-facing output leaked an internal provider follow-up parse error.");
    lines.push("- After: current output no longer exposes provider/parser internals.");
  }

  if (/Likely owner: unknown/.test(args.beforeText) && !/Likely owner: unknown/.test(args.afterText)) {
    lines.push("- Before: trivial outputs included `Likely owner: unknown`.");
    lines.push("- After: trivial outputs stay compact and omit the noisy unknown-owner line.");
  }

  if (/AssertionError:/.test(args.beforeText) && /passed/.test(args.afterText)) {
    lines.push("- Before: the command failed with expectation drift.");
    lines.push("- After: the same command now passes.");
  }

  if (lines.length === 0) {
    if (/passed/.test(args.afterText)) {
      lines.push("- After: the current command output is now passing.");
    } else {
      lines.push("- After: current output differs from the historical artifact; inspect the paired files for details.");
    }
  }

  return lines;
}

function buildIncidentSummary(entries: IncidentManifestEntry[]): string {
  const lines = [
    "# Phase 4a Incident Before vs After",
    "",
    "This file is auto-generated by `scripts/bench/generate-progress-report.ts`.",
    "",
    "It keeps the historical incident captures intact and summarizes how the current output differs today.",
    ""
  ];

  for (const entry of entries) {
    if (!entry.currentArtifactPath) {
      continue;
    }

    const beforeText = readFileSync(path.join(repoRoot, entry.artifactPath), "utf8");
    const afterText = readFileSync(path.join(repoRoot, entry.currentArtifactPath), "utf8");

    lines.push(`## ${entry.id}`);
    lines.push("");
    lines.push(`- Title: ${entry.title}`);
    lines.push(`- Historical: [${entry.artifactPath}](./${path.basename(entry.artifactPath)})`);
    lines.push(`- Current: [${entry.currentArtifactPath}](./${path.basename(entry.currentArtifactPath)})`);
    for (const line of summarizeIncidentDelta({
      id: entry.id,
      beforeText,
      afterText,
      recovered: entry.exactTextRecovered
    })) {
      lines.push(line);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function buildBenchmarkMarkdown(args: {
  packageVersion: string;
  presetReport: PresetBenchmarkReport;
  testStatusReport: TestStatusBenchmarkReport;
}): string {
  const lines = [
    "# Current Benchmark Report",
    "",
    "This file is auto-generated by `scripts/bench/generate-progress-report.ts`.",
    "",
    `- Version: \`${args.packageVersion}\``,
    `- Generated: \`${new Date().toISOString()}\``,
    "",
    "## Preset Aggregate",
    "",
    `- Cases: \`${args.presetReport.aggregate.totalCases}\``,
    `- Passed: \`${args.presetReport.aggregate.passed}\``,
    `- Avg reduction: \`${args.presetReport.aggregate.avgReductionPct?.toFixed?.(2) ?? args.presetReport.aggregate.avgReductionPct ?? "n/a"}%\``,
    `- Raw tokens: \`${args.presetReport.aggregate.totalRawTokens}\``,
    `- Reduced tokens: \`${args.presetReport.aggregate.totalReducedTokens}\``,
    "",
    "## Preset Breakdown",
    ""
  ];

  for (const preset of args.presetReport.byPreset) {
    lines.push(
      `- \`${preset.preset}\`: ${preset.passed}/${preset.caseCount} pass, avg reduction \`${preset.avgReductionPct?.toFixed?.(2) ?? preset.avgReductionPct ?? "n/a"}%\``
    );
  }

  lines.push("", "## Test-Status Aggregate", "");
  lines.push(
    `- Raw tokens: \`${args.testStatusReport.aggregate.primary.raw.tokens}\``
  );
  lines.push(
    `- Standard tokens: \`${args.testStatusReport.aggregate.primary.standard.tokens}\``
  );
  lines.push(
    `- Focused tokens: \`${args.testStatusReport.aggregate.primary.focused.tokens}\``
  );
  lines.push(
    `- Verbose tokens: \`${args.testStatusReport.aggregate.primary.verbose.tokens}\``
  );
  lines.push(
    `- Diagnose JSON tokens: \`${args.testStatusReport.aggregate.primary.diagnoseJson.tokens}\``
  );
  lines.push(
    `- Standard reduction: \`${formatPct(
      args.testStatusReport.aggregate.primary.raw.tokens,
      args.testStatusReport.aggregate.primary.standard.tokens
    )}\``
  );
  lines.push("", "## Test-Status Fixture Snapshot", "");

  for (const fixture of args.testStatusReport.fixtures) {
    lines.push(
      `- \`${fixture.name}\`: decision=\`${fixture.decision}\`, owner=\`${fixture.primarySuspectKind}\`, unknown buckets=\`${fixture.unknownBucketCount}\`, standard reduction=\`${formatPct(
        fixture.primary.raw.tokens,
        fixture.primary.standard.tokens
      )}\``
    );
  }

  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const packageJson = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8")) as {
    version: string;
  };
  const presetReport = runJsonScript([
    "scripts/bench/preset-reduction.ts"
  ]) as PresetBenchmarkReport;
  const testStatusReport = runJsonScript([
    "scripts/bench/test-status-ab.ts",
    "--json",
    "--include-rendered"
  ]) as TestStatusBenchmarkReport;
  const incidentModule = await import(
    pathToFileURL(path.join(repoRoot, "test/fixtures/bench/test-status/incidents.ts")).href
  );
  const incidentEntries = incidentModule.testStatusIncidentArtifacts as IncidentManifestEntry[];

  const historyDir = path.join(repoRoot, "benchmarks", "history");
  ensureDir(historyDir);

  const combinedJson = {
    version: packageJson.version,
    generatedAt: new Date().toISOString(),
    presetBenchmarks: presetReport,
    testStatusBenchmarks: testStatusReport
  };
  writeFileSync(
    path.join(historyDir, "current-benchmark-report.json"),
    `${JSON.stringify(combinedJson, null, 2)}\n`
  );
  writeFileSync(
    path.join(historyDir, "current-benchmark-report.md"),
    buildBenchmarkMarkdown({
      packageVersion: packageJson.version,
      presetReport,
      testStatusReport
    })
  );

  if (args.snapshotLabel) {
    const snapshotDir = path.join(historyDir, "snapshots");
    ensureDir(snapshotDir);
    writeFileSync(
      path.join(snapshotDir, `${args.snapshotLabel}.json`),
      `${JSON.stringify(combinedJson, null, 2)}\n`
    );
    writeFileSync(
      path.join(snapshotDir, `${args.snapshotLabel}.md`),
      buildBenchmarkMarkdown({
        packageVersion: packageJson.version,
        presetReport,
        testStatusReport
      })
    );
  }

  const incidentSummary = buildIncidentSummary(incidentEntries);
  writeFileSync(
    path.join(
      repoRoot,
      "examples",
      "incidents",
      "test-status-phase4a",
      "before-vs-after-summary.md"
    ),
    incidentSummary
  );
}

await main();
